import Foundation

struct Localizable {
    static func text(_ key: String, isEnglish: Bool) -> String {
        return isEnglish ? english[key] ?? key : spanish[key] ?? key
    }
    
    private static let english: [String: String] = [
        "terminal.command": "photocleanup",
        "terminal.script": "./cleanup.sh",
        "system.ready": "SYSTEM_STATUS: READY",
        "system.gallery": "GALLERY_SIZE",
        "system.storage": "STORAGE_MODE: active",
        "items": "items",
        "select.filter": "SELECT_FILTER:",
        "batch.size": "BATCH_SIZE:",
        "execute": "EXECUTE",
        "filter.random": "RANDOM_MODE",
        "filter.screenshots": "SCREENSHOT_FILTER",
        "filter.selfies": "PHOTO_ONLY",
        "filter.blurred": "RECENT_BATCH",
        "filter.duplicates": "BURST_DETECTION",
        "filter.thisMonth": "CURRENT_MONTH",
        "filter.lastYear": "ARCHIVE_MODE",
        "desc.random": "Completely randomized selection",
        "desc.screenshots": "Screen captures detected by resolution",
        "desc.selfies": "All photos from your library",
        "desc.blurred": "Quick batch of recent photos",
        "desc.duplicates": "Photos taken in burst mode",
        "desc.thisMonth": "Files from current month only",
        "desc.lastYear": "Photos from previous year",
        "keep": "KEEP",
        "delete": "DELETE",
        "photo": "Photo",
        "of": "of",
        "hold.view": "Hold to view full screen",
        "review.title": "DELETION_SUMMARY",
        "review.marked": "marked for deletion",
        "review.cancel": "CANCEL",
        "review.confirm": "CONFIRM_DELETE",
        "review.deleting": "Deleting files...",
        "review.success": "Files deleted successfully",
        "review.new": "NEW_SESSION",
        "review.great": "GREAT_JOB",
        "review.safe": "No files marked for deletion. All safe.",
        "access.denied": "ACCESS_DENIED",
        "permission.required": "PERMISSION_REQUIRED: photo_library",
        "permission.desc1": "This application requires access to your",
        "permission.desc2": "photo library to organize media files.",
        "grant.access": "GRANT_ACCESS",
        "loading.scan": "SCANNING_FILESYSTEM",
        "loading.analyze": "ANALYZING_METADATA",
        "loading.thumbnails": "LOADING_THUMBNAILS",
        "loading.prepare": "PREPARING_INTERFACE",
        "error.no.files": "ERROR: NO_FILES_FOUND",
        "status.empty": "STATUS: gallery_empty",
        "retry": "RETRY",
        "settings.title": "CONFIGURATION",
        "settings.username": "USERNAME:",
        "settings.language": "LANGUAGE:",
        "settings.english": "English",
        "settings.spanish": "Español",
        "settings.save": "SAVE",
        "settings.placeholder": "Enter your username"
    ]
    
    private static let spanish: [String: String] = [
        "terminal.command": "limpieza-fotos",
        "terminal.script": "./limpiar.sh",
        "system.ready": "ESTADO_SISTEMA: LISTO",
        "system.gallery": "TAMAÑO_GALERIA",
        "system.storage": "MODO_ALMACENAMIENTO: activo",
        "items": "elementos",
        "select.filter": "SELECCIONAR_FILTRO:",
        "batch.size": "TAMAÑO_LOTE:",
        "execute": "EJECUTAR",
        "filter.random": "MODO_ALEATORIO",
        "filter.screenshots": "FILTRO_CAPTURAS",
        "filter.selfies": "SOLO_FOTOS",
        "filter.blurred": "LOTE_RECIENTE",
        "filter.duplicates": "DETECCION_RAFAGA",
        "filter.thisMonth": "MES_ACTUAL",
        "filter.lastYear": "MODO_ARCHIVO",
        "desc.random": "Selección completamente aleatoria",
        "desc.screenshots": "Capturas de pantalla detectadas por resolución",
        "desc.selfies": "Todas las fotos de tu biblioteca",
        "desc.blurred": "Lote rápido de fotos recientes",
        "desc.duplicates": "Fotos tomadas en modo ráfaga",
        "desc.thisMonth": "Archivos del mes actual solamente",
        "desc.lastYear": "Fotos del año anterior",
        "keep": "CONSERVAR",
        "delete": "ELIMINAR",
        "photo": "Foto",
        "of": "de",
        "hold.view": "Mantén presionado para ver completo",
        "review.title": "RESUMEN_ELIMINACION",
        "review.marked": "marcadas para eliminar",
        "review.cancel": "CANCELAR",
        "review.confirm": "CONFIRMAR_ELIMINAR",
        "review.deleting": "Eliminando archivos...",
        "review.success": "Archivos eliminados exitosamente",
        "review.new": "NUEVA_SESION",
        "review.great": "EXCELENTE_TRABAJO",
        "review.safe": "No se marcaron archivos. Todo está seguro.",
        "access.denied": "ACCESO_DENEGADO",
        "permission.required": "PERMISO_REQUERIDO: biblioteca_fotos",
        "permission.desc1": "Esta aplicación requiere acceso a tu",
        "permission.desc2": "biblioteca de fotos para organizar archivos.",
        "grant.access": "CONCEDER_ACCESO",
        "loading.scan": "ESCANEANDO_SISTEMA",
        "loading.analyze": "ANALIZANDO_METADATOS",
        "loading.thumbnails": "CARGANDO_MINIATURAS",
        "loading.prepare": "PREPARANDO_INTERFAZ",
        "error.no.files": "ERROR: NO_SE_ENCONTRARON_ARCHIVOS",
        "status.empty": "ESTADO: galeria_vacia",
        "retry": "REINTENTAR",
        "settings.title": "CONFIGURACION",
        "settings.username": "NOMBRE_USUARIO:",
        "settings.language": "IDIOMA:",
        "settings.english": "English",
        "settings.spanish": "Español",
        "settings.save": "GUARDAR",
        "settings.placeholder": "Ingresa tu nombre de usuario"
    ]
}

